### ISSUE TITLE
Wrong event order: eventstore-postgresql-serverless

### ISSUE THREAD

**Issue by alexslavr** [reimagined/resolve#1866] opened 2021-05-13 10:37 UTC
Read model receives events in the wrong order after migration to reSolve v0.30.2.

**Comment by IhostVlad** [comment] 2021-05-13 10:45
It's postgres-serverless eventstore issue in loadEvents method, caused by mixing extra-small and extra-large events, which have size difference in several magnitude order
Will be fixed in next path version

**Closed** 2021-05-14 10:41 UTC
Labels: bug, severity: major
