### ISSUE TITLE
503 ERROR in browser when trying to access my application

### ISSUE THREAD

**Issue by pavsenin** [reimagined/resolve#2146] opened 2021-11-23 13:42 UTC
**Describe the bug**
Cannot access the application.

**To Reproduce**

1. Go to 'https://ddev.testcafe.io/'

**Expected behavior**
The application is opened.

**Screenshots**
![image](https://user-images.githubusercontent.com/761797/143034803-6c965dca-2773-4b31-a377-442e6cc3fb97.png)

**Comment by pavsenin** [comment] 2021-11-23 14:41
May be duplicate of #2125

**Comment by MrCheater** [comment] 2021-11-24 18:53
Duplicate of #2125

**Closed by MrCheater** 2021-11-24 18:53 UTC
